#
# Makefile rules for the cvec package
#
KEXT_NAME = json
KEXT_SOURCES = src/json.cc
KEXT_LDFLAGS = -lstdc++

# include shared GAP package build system
GAPPATH = /Users/cheldt/Documents/Code/GAP/GAP-4.14.0
include Makefile.gappkg
