#
# Makefile rules for the crypting package
#
KEXT_NAME = crypting
KEXT_SOURCES = src/crypting.c

# include shared GAP package build system
GAPPATH = /Users/cheldt/Documents/Code/GAP/GAP-4.14.0
include Makefile.gappkg
