#
# Makefile rules for the orb package
#
KEXT_NAME = orb
KEXT_SOURCES = src/orb.c

# include shared GAP package build system
GAPPATH = /Users/cheldt/Documents/Code/GAP/gap-4.14.0
include Makefile.gappkg
