#
# Makefile rules for the DeepThought package
#
KEXT_NAME = DeepThought
KEXT_SOURCES = src/DeepThought.c

# include shared GAP package build system
GAPPATH = /Users/cheldt/Documents/Code/GAP/gap-4.14.0
include Makefile.gappkg
