#
# Makefile rules for the datastructures package
#
KEXT_NAME = datastructures

KEXT_SOURCES =
KEXT_SOURCES += src/avl.c
KEXT_SOURCES += src/binaryheap.c
KEXT_SOURCES += src/datastructures.c
KEXT_SOURCES += src/hashfunctions.c
KEXT_SOURCES += src/hashmap.c
KEXT_SOURCES += src/pairingheap.c
KEXT_SOURCES += src/skiplist.c
KEXT_SOURCES += src/uf.c

# include shared GAP package build system
GAPPATH = /Users/cheldt/Documents/Code/GAP/gap-4.14.0
include Makefile.gappkg
