#
# Makefile rules for the profiling package
#
KEXT_NAME = profiling
KEXT_SOURCES = src/profiling.cc src/md5.cc
KEXT_LDFLAGS = -lstdc++

# include shared GAP package build system
GAPPATH = /Users/cheldt/Documents/Code/GAP/GAP-4.14.0
include Makefile.gappkg
