#
# Makefile rules for the cvec package
#
KEXT_NAME = cvec
KEXT_SOURCES = src/cvec.c

# include shared GAP package build system
GAPPATH = /Users/cheldt/Documents/Code/GAP/gap-4.14.0
include Makefile.gappkg
